# Toy dataset — validating the ranking methodology

We construct a synthetic panel of 5 forecasters with **known** standard deviations. Forecasts are simulated as `realized + N(0, sigma_i)` using actual NGDP advance estimates as the realized series. Since the true ranking is determined by the sigmas, we can check whether the procedure recovers it.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from rankci import (
    rank_ci_stepwise_pairwise,
    load_rtdsm,
)
from rankci.data import advance_vintage_col, get_advance_estimate

## 1. Realized series

Use the RTDSM advance estimates as the "true" realized values. We pick a window of quarters where vintages are available.

In [2]:
noutput = load_rtdsm("../data/NOUTPUTQvQd.xlsx")

# Pick a window of target quarters
quarters = [(y, q) for y in range(1970, 2020) for q in range(1, 5)]

realized = pd.Series(
    [get_advance_estimate(y, q, noutput) for y, q in quarters],
    index=pd.MultiIndex.from_tuples(quarters, names=["YEAR", "QUARTER"]),
    name="realized",
).dropna()

print(f"Realized series: {len(realized)} quarters, "
      f"{realized.index[0]} → {realized.index[-1]}")
realized.head()

Realized series: 199 quarters, (1970, 1) → (2019, 4)

YEAR  QUARTER
1970  1           960.4
      2           970.1
      3           985.2
      4           990.9
1971  1          1018.4
Name: realized, dtype: float64

## 2. Forecasters

Each forecaster `i` draws `error_t ~ N(0, sigma_i)` independently across quarters.
True ranking by MSE is determined by `sigma_i^2` — lower sigma is a better forecaster.

In [3]:
# Five forecasters with different noise levels (in bn $)
sigmas = {
    "F1":  50.0,
    "F2":  75.0,
    "F3": 100.0,
    "F4": 150.0,
    "F5": 200.0,
}
truth = pd.DataFrame({
    "sigma": pd.Series(sigmas),
    "true_MSE": pd.Series(sigmas) ** 2,
})
truth["true_rank"] = truth["true_MSE"].rank(method="min").astype(int)
truth

    sigma  true_MSE  true_rank
F1   50.0    2500.0          1
F2   75.0    5625.0          2
F3  100.0   10000.0          3
F4  150.0   22500.0          4
F5  200.0   40000.0          5

## 3. Simulate forecasts and errors

In [4]:
rng = np.random.default_rng(42)
n  = len(realized)

# errors[t, i] ~ N(0, sigmas[i])
errors = pd.DataFrame(
    {fid: rng.normal(0, s, size=n) for fid, s in sigmas.items()},
    index=realized.index,
)

# forecast = realized + error
forecasts = errors.add(realized, axis=0)

# squared errors — this is the panel X for the ranking procedure
X_panel = errors ** 2

print("Sample of simulated data:")
preview = pd.DataFrame({"realized": realized, **{f"{c}_forecast": forecasts[c] for c in forecasts.columns}})
preview.head()

Sample of simulated data:

              realized  F1_forecast  F2_forecast  F3_forecast  F4_forecast  \
YEAR QUARTER
1970 1           960.4   975.635854   948.141783  1013.406471  1082.290193
     2           970.1   918.100795   995.418091   899.632674  1006.348958
     3           985.2  1022.722560  1090.761140   967.238859   718.955691
     4           990.9  1037.928236   997.693868  1010.577610  1068.211560
1971 1          1018.4   920.848241  1066.695409  1100.452848   931.769167

              F5_forecast
YEAR QUARTER
1970 1        1159.540277
     2        1181.944748
     3        1190.367369
     4         998.682641
1971 1         849.390934

In [5]:
# Empirical MSE per forecaster — should be close to sigma_i^2
empirical = pd.DataFrame({
    "sigma":         pd.Series(sigmas),
    "true_MSE":      pd.Series(sigmas) ** 2,
    "empirical_MSE": X_panel.mean(),
})
empirical

    sigma  true_MSE  empirical_MSE
F1   50.0    2500.0    1946.508438
F2   75.0    5625.0    5827.625779
F3  100.0   10000.0   10224.138237
F4  150.0   22500.0   23411.574578
F5  200.0   40000.0   41276.501172

## 4. Apply the ranking methodology

Run the stepwise bootstrap with pairwise NW-HAC standard errors. Since the true ranking is `F1 < F2 < F3 < F4 < F5`, we expect the procedure to recover an informative confidence set.

In [6]:
X = X_panel.values
ids = X_panel.columns.tolist()

out = rank_ci_stepwise_pairwise(X, alpha=0.05, B=5000, seed=42)

results = pd.DataFrame({
    "ID":         ids,
    "true_sigma": [sigmas[i] for i in ids],
    "MSE":        out["theta_hat"].round(1),
    "CI_lower":   out["rank_ci"][:, 0],
    "CI_upper":   out["rank_ci"][:, 1],
}).sort_values("MSE")
results.index = range(1, len(results) + 1)
results.index.name = "Est_Rank"
results

=== Pairwise shared observations ===
  Min: 199, Mean: 199.0, Max: 199
  Pairs with < 20 shared obs: 0

=== Test statistics (delta_hat / se) ===
  Max: 9.3740, Pairs with t > 1.96: 10

          ID  true_sigma      MSE  CI_lower  CI_upper
Est_Rank
1         F1        50.0   1946.5         1         1
2         F2        75.0   5827.6         2         2
3         F3       100.0  10224.1         3         3
4         F4       150.0  23411.6         4         4
5         F5       200.0  41276.5         5         5

In [7]:
print(results)

          ID  true_sigma      MSE  CI_lower  CI_upper
Est_Rank
1         F1        50.0   1946.5         1         1
2         F2        75.0   5827.6         2         2
3         F3       100.0  10224.1         3         3
4         F4       150.0  23411.6         4         4
5         F5       200.0  41276.5         5         5